spring.datasource.url=jdbc:mysql://localhost:3306/university_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Spring123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=dTJ3WkhNRkxQV1hKNHF5QjZtOXZSZ0hZVWNBZXRwU2E=
jwt.expiration-ms=86400000